/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiShotRouteImport } from './routes/api/shot'
import { Route as ApiTraceRouteImport } from './routes/api/trace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShotRoute = ApiShotRouteImport.update({
  id: '/api/shot',
  path: '/api/shot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTraceRoute = ApiTraceRouteImport.update({
  id: '/api/trace',
  path: '/api/trace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/shot': typeof ApiShotRoute
  '/api/trace': typeof ApiTraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/shot': typeof ApiShotRoute
  '/api/trace': typeof ApiTraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/shot': typeof ApiShotRoute
  '/api/trace': typeof ApiTraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/shot' | '/api/trace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/shot' | '/api/trace'
  id: '__root__' | '/' | '/api/shot' | '/api/trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiShotRoute: typeof ApiShotRoute
  ApiTraceRoute: typeof ApiTraceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shot': {
      id: '/api/shot'
      path: '/api/shot'
      fullPath: '/api/shot'
      preLoaderRoute: typeof ApiShotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trace': {
      id: '/api/trace'
      path: '/api/trace'
      fullPath: '/api/trace'
      preLoaderRoute: typeof ApiTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiShotRoute: ApiShotRoute,
  ApiTraceRoute: ApiTraceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
